"""empty message

Revision ID: d33fc17c419b
Revises: ece181b3623c
Create Date: 2018-04-26 21:37:49.849520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd33fc17c419b'
down_revision = 'ece181b3623c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bay_owner', sa.Column('uploaded_image_name', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_bay_owner_uploaded_image_name'), 'bay_owner', ['uploaded_image_name'], unique=True)
    op.drop_index('ix_bay_owner_upload_image_name', table_name='bay_owner')
    op.drop_column('bay_owner', 'upload_image_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bay_owner', sa.Column('upload_image_name', mysql.VARCHAR(length=60), nullable=True))
    op.create_index('ix_bay_owner_upload_image_name', 'bay_owner', ['upload_image_name'], unique=True)
    op.drop_index(op.f('ix_bay_owner_uploaded_image_name'), table_name='bay_owner')
    op.drop_column('bay_owner', 'uploaded_image_name')
    # ### end Alembic commands ###
