"""empty message

Revision ID: ece181b3623c
Revises: 
Create Date: 2018-04-26 21:25:44.261961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece181b3623c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bay_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('national_id', sa.String(length=60), nullable=True),
    sa.Column('upload_image_name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bay_owner_first_name'), 'bay_owner', ['first_name'], unique=False)
    op.create_index(op.f('ix_bay_owner_last_name'), 'bay_owner', ['last_name'], unique=False)
    op.create_index(op.f('ix_bay_owner_national_id'), 'bay_owner', ['national_id'], unique=True)
    op.create_index(op.f('ix_bay_owner_upload_image_name'), 'bay_owner', ['upload_image_name'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('bay_owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bay_owner_id'], ['bay_owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bay_number'), 'bay', ['number'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_bay_number'), table_name='bay')
    op.drop_table('bay')
    op.drop_table('role')
    op.drop_index(op.f('ix_bay_owner_upload_image_name'), table_name='bay_owner')
    op.drop_index(op.f('ix_bay_owner_national_id'), table_name='bay_owner')
    op.drop_index(op.f('ix_bay_owner_last_name'), table_name='bay_owner')
    op.drop_index(op.f('ix_bay_owner_first_name'), table_name='bay_owner')
    op.drop_table('bay_owner')
    # ### end Alembic commands ###
